 include(InstallRequiredSystemLibraries)


set(CPACK_PACKAGE_CONTACT "your_email@student.bmstu.ru")
set(CPACK_PACKAGE_VERSION_MAJOR ${PRINT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PRINT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PRINT_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${PRINT_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION "${PRINT_VERSION}")

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Solver application for quadratic equations")
set(CPACK_PACKAGE_VENDOR "BMSTU_IU8")

set(CPACK_PACKAGE_DESCRIPTION_FILE "${PROJECT_SOURCE_DIR}/DESCRIPTION")
set(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${PROJECT_SOURCE_DIR}/README.md")

set(CPACK_GENERATOR "TGZ;ZIP")

set(CPACK_RPM_PACKAGE_NAME "solver-application")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Development/Tools")
set(CPACK_RPM_PACKAGE_RELEASE 1)

set(CPACK_DEBIAN_PACKAGE_NAME "solver-application-dev")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.0")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

set(CPACK_WIX_PACKAGE_NAME "SolverProject")
set(CPACK_WIX_PRODUCT_GUID "12345678-ABCD-EF12-3456-7890ABCDEF12")
set(CPACK_WIX_UPGRADE_GUID "87654321-ABCD-EF12-3456-7890ABCDEF12")

set(CPACK_RESOURCE_FILE_LICENSE "")

set(CPACK_DMG_VOLUME_NAME "SolverProject Setup")
set(CPACK_DMG_FORMAT "UDZO")

include(CPack)

