name: Share Releases

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --- LINUX STEP ---
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y rpm dpkg

    - name: Run CPack on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -S . -B _build -DCMAKE_BUILD_TYPE=Release
        cmake --build _build --config Release
        cpack --config _build/CPackConfig.cmake -G "DEB"
        cpack --config _build/CPackConfig.cmake -G "RPM"
        cpack --config _build/CPackConfig.cmake -G "TGZ"

    # --- WINDOWS STEP ---
    - name: Run CPack on Windows
      if: matrix.os == 'windows-latest'
      run: |
        cmake -S . -B _build -DCMAKE_BUILD_TYPE=Release
        cmake --build _build --config Release
        cpack --config _build/CPackConfig.cmake -G "WIX" -C Release

    # --- MACOS STEP ---
    - name: Run CPack on macOS
      if: matrix.os == 'macos-latest'
      run: |
        cmake -S . -B _build -DCMAKE_BUILD_TYPE=Release
        cmake --build _build --config Release
        cpack --config _build/CPackConfig.cmake -G "DragNDrop"

    # --- UPLOAD STEP ---
    - name: Create and Upload Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          _build/*.deb
          _build/*.rpm
          _build/*.tar.gz
          _build/*.msi
          _build/*.dmg
